### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lightpriest** [tmeasday/validation-error#16]
Hi! Is it possible to add a license to this project?
It's a transitive dependency of some popular packages, which makes it a bit problematic to use since it's not licensed formally.

**Comment by robsecord** [comment]
+1
Publishing software without a license means that anyone attempting to use it would be in violation of copyright. If you could please add an MIT or another distribution-friendly license, that would be appreciated!
Thanks in advance!

**Comment by lukejagodzinski** [comment]
License added
@stubailo I think that as all other libraries it should be MIT, am I right?

**Comment by stubailo** [comment]
Yep!

**Comment by stubailo** [comment]
Thanks for adding it @jagi :]
