### ISSUE TITLE
If an error is thrown, it's not possible to determine which fields were wrong from the Chrome error console.

### ISSUE THREAD

**Issue by stubailo** [tmeasday/validation-error#2]
https://www.dropbox.com/s/65xcgdoj0uyasl3/Screenshot%202015-12-09%2011.59.39.png?dl=0

**Comment by aldeed** [comment]
@stubailo My implementation of this in collection2 adds the first invalid key message as the overall error message. Maybe do that?

See https://github.com/aldeed/meteor-collection2/blob/master/lib/collection2.js#L326-L330

**Comment by stubailo** [comment]
Good idea.

**Comment by aldeed** [comment]
The SimpleSchema half of this is done in https://github.com/aldeed/meteor-simple-schema/commit/7bcfbf1e7d3ac3d6f0a6c756965cfeca5ad56b4a and released as 1.5.2
