### ISSUE TITLE
Publish 0.5.1 version

### ISSUE THREAD

**Issue by lukejagodzinski** [tmeasday/validation-error#9]
@stubailo
There is a bug in the package that makes it not usable. It was introduced by my last update so sorry for that. I will pay more attention to it in the future. I've just made an update but haven't been testing it.

It goes about how the class is declared. It has to be declared in the global scope if used without the `export` statement. For Meteor 1.2 it has to be exported using `api.export` and for that case the `ValidationError` class has to be defined in the "global" scope instead locally with the `var` https://github.com/meteor/validation-error/commit/8321c55a736a74d02f6275924c5da4f2b4a790ad

I've fixed this bug and bumped version to `0.5.1` so you can just publish it.

**Comment by lukejagodzinski** [comment]
I was trying to find out packages and finally figured it out `meteor test-packages --release 1.3-beta.11 ./ --port 4000 --unit --driver-package avital:mocha`. I hope it won't be so complicated in the final Meteor 1.3 release :)

**Comment by stubailo** [comment]
```
➜  validation-error git:(master) meteor admin maintainers mdg:validation-error

The maintainers for mdg:validation-error are:
mdg
jagi
aldeed
```

You can publish the new version yourself!

But please be more careful in the future.

**Comment by lukejagodzinski** [comment]
Oh ok I didn't know that :)

Yes I will. I haven't thought that it will be published right away :)
